### ISSUE TITLE
[No workaround] Shell Integration doesn't work for other users, and Unregister shell extension does nothing (cannot Register)

### ISSUE THREAD

**Issue by scscgit** [WinMerge/winmerge#2419]
When I switch to a different user on Windows 10, there is no shell integration to run WinMerge by right-clicking a file. It originally worked on my first user.

Thinking the installation only installed it for the first user, I uninstalled old version, and then installed the latest `WinMerge-2.16.42.1-x64-Setup.exe` variant for all users.

When I tried it on the second user, there was still no shell integration. So I went to settings and tried both buttons (Unregister shell extension and Register shell extension for current user only). They do absolutely nothing. And I realized that it doesn't work on my first user anymore either.
![image](https://github.com/user-attachments/assets/001435a8-b42c-40df-af94-a7b6138503b0)

**Comment by sdottaka** [comment]
I was unable to reproduce this issue.
Does the second user have the "Add to context menu" checkbox checked?

**Comment by scscgit** [comment]
Yes, the options look the same on both users.

Are there any logs for the shell integration, or any debugging steps I could try?

**Comment by Flyingscool** [comment]
I didn't realize how similar our bug reports are.  I fixed the problem by copying the ShellExtensionX64.dll to ShellExtensionU.dll.

As I noted in my bug report, two windows pop up when clicking the "Register Shell Extension" buttons (I'm on Windows 11 Home on the machine I was having the context menu problem with). In the first window, when I displayed the details, it mentioned the ShellExtensionX64.dll, and in the second window it mentioned the ShellExtensionU.dll file. ShellExtensionU.dll did not exist in the directory, so I copied ShellExtensionX64.dll to ShellExtensionU.dll unregistered the options, then clicked the two Register buttons, and it added the context menu option.

**Comment by scscgit** [comment]
Yes, both users are admins. I also tried to run WinMerge as admin, and I still cannot register the shell extensions in either of them, because there is only the Unregister button. And I already have the `ShellExtensionU.dll` file there. Even if I copy it to `ShellExtensionX64.dll`, the Unregister button still doesn't cause the Register button to become available.

**Comment by realsobek** [comment]
I am using WinMerge 2.16.44.0 on Microsoft Windows 10 64-bit. I lost the WinMerge context menu item in Windows Explorer after upgrading from WinMerge 2.14 (might have been "uninstall and install from scratch"). "WinMerge -- Edit -- Options... -- Shell Integration -- Explorer: [x] Add to context menu" is set and [Unregister shell extension] is clickable.

I noticed a missing empty space in WinMerge's regsvr32 calls, which fails un- & registration of ShellExtensionU.dll. You must register manually.

In "C:\Program Files\WinMerge" there are (among other files) different files:
- ShellExtensionU.dll
- ShellExtensionX64.dll.8340.old

### unsuccessful
I include this, because I do not know if it is required or not.
At first I ran regedit.exe as administrator and replaced all occurances of "C:\Program Files\WinMerge\ShellExtensionX64.dll" with "C:\Program Files\WinMerge\ShellExtensionU.dll" and rebooted the computer to no avail in:
- Computer\HKEY_CLASSES_ROOT\CLSID\{4E716236-AA30-4C65-B225-D68BBA81E9C2}\InprocServer32
- Computer\HKEY_CLASSES_ROOT\TypeLib\{06029E17-28B5-456A-B866-4E79D98612FD}\1.0\0\win64

Same as:
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{4E716236-AA30-4C65-B225-D68BBA81E9C2}\InprocServer32
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{06029E17-28B5-456A-B866-4E79D98612FD}\1.0\0\win64
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\TypeLib\{06029E17-28B5-456A-B866-4E79D98612FD}\1.0\0\win64

### successful
I ran "WinMerge -- Edit -- Options... -- Shell Integration -- Explorer: Explorer: [Unregister shell extension]". In the administrative credentials request window click on "Show more details". You see for the first command:
`"C:\Windows\system32\regsvr32.exe" /s /u "C:\Program Files\WinMerge\ShellExtensionX64.dll"`
and after answering for the second command (**notice the missing empty space after "/u"**):
`"C:\Windows\system32\regsvr32.exe" /s /u"C:\Program Files\WinMerge\ShellExtensionU.dll"`

In cmd.exe running `regsvr32 /u"C:\Program Files\WinMerge\ShellExtensionU.dll"` fails, i.e. prints regsvr32 help.
In cmd.exe running `regsvr32 /u "C:\Program Files\WinMerge\ShellExtensionU.dll"` fails with error message:

> RegSvr32
>
> The module "C:\Program Files\WinMerge\ShellExtensionU.dll" was loaded but the call to DllRegisterServer failed with error code 0x80070005.
>
> For more information about this problem, search online using the error code as a search term.
That means "run in administrative cmd". Running in administrative cmd succeded. Running it again failed with error 0x8002801c (not registered).
> [OK]

Error 0x80070005 means "run in administrative cmd". Run in administrative cmd `regsvr32 /u "C:\Program Files\WinMerge\ShellExtensionX64.dll.8340.old"` succeeds.

#### successful registration
The button "WinMerge -- Edit -- Options... -- Shell Integration -- Explorer: [Register shell extension]" is clickable again. Clicking it you can see in "Show more details":
`"C:\Windows\system32\regsvr32.exe" /s "C:\Program Files\WinMerge\ShellExtensionX64.dll"`
and (**notice the missing empty space after "/s"**):
`"C:\Windows\system32\regsvr32.exe" /s"C:\Program Files\WinMerge\ShellExtensionU.dll"`

Running in administrative cmd `regsvr32 "C:\Program Files\WinMerge\ShellExtensionX64.dll.8340.old"` and `regsvr32 "C:\Program Files\WinMerge\ShellExtensionU.dll"` makes the WinMerge context menu item in Windows Explorer reappear.

### unknown
I do not know if "WinMerge -- Edit -- Options... -- Shell Integration -- Explorer: [Register shell extension for current user only]" lacks an empty space too. It did not work for me. I did not trace it (with Sysinternal's "Process Monitor").

**Comment by sdottaka** [comment]
@realsobek Thank you for reporting this. The issue of ShellExtensionU.dll not being properly registered and unregistered has been fixed in commit 4e8e21e.
I'm not sure why ShellExtensionX64.dll.8340.old remains, but it seems that the WinMerge installer did not install ShellExtesionX64.dll correctly, so I recommend you reinstall it.

**Comment by scscgit** [comment]
@sdottaka Thanks, updating seems to have fixed it for me.
Just a small note: should this fix not have been included in the latest release notes? ([v2.16.47](https://github.com/WinMerge/winmerge/releases/tag/v2.16.47))

**Comment by sdottaka** [comment]
This fix is actually mentioned in the release notes for v2.16.47. 

![Image](https://github.com/user-attachments/assets/8644a599-0de8-47a4-9c45-7df884fe8b77)
