### ISSUE TITLE
WinMerge shows the timestamp of the non-existent file

### ISSUE THREAD

**Issue by vyv03354** [WinMerge/winmerge#2764]
Steps to reproduce:
Compare empty and non-empty folders

Actual result:
Shows "1970/01/01 9:00:00" in the date field.
![Image](https://github.com/user-attachments/assets/b267d0e1-b666-4c50-b37d-a3320fca94b0)

Expected result:
Date field should be empty.

I guess this is a regression from #2714.

**Comment by sdottaka** [comment]
We have fixed this issue in commit f323510.
Thank you for reporting it.

**Comment by TrevoIT** [comment]
<img width="266" height="500" alt="Image" src="https://github.com/user-attachments/assets/1ad1f96d-f784-4071-b95c-be9cacbf5ebc" />
Still happening

**Comment by sdottaka** [comment]
>  Still happening

We plan to release a fix for this at the end of this month.

**Comment by sdottaka** [comment]
Fixed in WinMerge 2.16.50 (now released). Closing.
